### ISSUE TITLE
gcalcli  agenda --detail longurl 

### ISSUE THREAD

**Issue by hubecker** [mumpitzstuff/fhem-GCALVIEW#3]
usage: gcalcli agenda [-h]
                      [--details {calendar,location,length,reminders,description,url,attendees,email,attachments,all}]

longurl ist mit version:
gcalcli v4.1.1 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)
und
gcalcli v4.2.0 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)

nicht mehr verfügbar

**Comment by mumpitzstuff** [comment]
fixed
