### ISSUE TITLE
falsches argument --configFolder

### ISSUE THREAD

**Issue by hubecker** [mumpitzstuff/fhem-GCALVIEW#4]
Auch das argument --configFolder heißt jetzt --config-folder

`2019.09.27 12:41:22 3: myGAbfall: export PYTHONIOENCODING=utf8 && gcalcli agenda 09/27/2019 10/27/2019 --configFolder /opt/fhem --calendar "Abfallkalender" --details calendar --details url --details location --details description --details email --nocache --tsv
2019.09.27 12:41:22 3: myGAbfall: something went wrong (check your parameters) - usage: gcalcli [-h] [--client-id CLIENT_ID] [--client-secret CLIENT_SECRET]
               [--config-folder CONFIG_FOLDER] [--noincluderc]
               [--calendar CALENDAR] [--default-calendar DEFAULTCALENDAR]
               [--locale LOCALE] [--refresh] [--nocache] [--conky] [--nocolor]
               [--lineart {fancy,unicode,ascii}]
gcalcli: error: unrecognized arguments: --configFolder /opt/fhem
`

**Comment by mumpitzstuff** [comment]
should be fixed now
